// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProteinStore.API.Data;

#nullable disable

namespace ProteinStore.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260112210900_AddNewProducts")]
    partial class AddNewProducts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SubCategory")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Weight")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Protein",
                            Description = "Advanced whey protein.",
                            ImageUrl = "/products/nitro-tech.jpg",
                            Name = "MuscleTech Nitro Tech Whey",
                            Price = 55m,
                            SubCategory = "Whey",
                            Weight = "4 lbs"
                        },
                        new
                        {
                            Id = 2,
                            Category = "Protein",
                            Description = "Premium whey protein.",
                            ImageUrl = "/products/ghost-whey.jpg",
                            Name = "Ghost Whey Protein",
                            Price = 48m,
                            SubCategory = "Whey",
                            Weight = "2 lbs"
                        },
                        new
                        {
                            Id = 3,
                            Category = "Protein",
                            Description = "Ultra premium whey.",
                            ImageUrl = "/products/bpi-whey-hd.jpg",
                            Name = "BPI Whey HD",
                            Price = 52m,
                            SubCategory = "Whey",
                            Weight = "4.07 lbs"
                        },
                        new
                        {
                            Id = 4,
                            Category = "Protein",
                            Description = "Clean isolate.",
                            ImageUrl = "/products/raw-isotholate.jpg",
                            Name = "RAW Isotholate Protein",
                            Price = 60m,
                            SubCategory = "Isolate",
                            Weight = "2.9 lbs"
                        },
                        new
                        {
                            Id = 5,
                            Category = "Protein",
                            Description = "Mass whey.",
                            ImageUrl = "/products/big-ramy-big-whey.jpg",
                            Name = "Big Ramy Big Whey",
                            Price = 58m,
                            SubCategory = "Whey",
                            Weight = "5 lbs"
                        },
                        new
                        {
                            Id = 6,
                            Category = "Protein",
                            Description = "Clean blend.",
                            ImageUrl = "/products/rule1-whey.jpg",
                            Name = "Rule 1 Whey Blend",
                            Price = 45m,
                            SubCategory = "Whey",
                            Weight = "2 lbs"
                        },
                        new
                        {
                            Id = 7,
                            Category = "Protein",
                            Description = "Hydro isolate.",
                            ImageUrl = "/products/dymatize-iso100.jpg",
                            Name = "Dymatize ISO100",
                            Price = 65m,
                            SubCategory = "Isolate",
                            Weight = "1.43 lbs"
                        },
                        new
                        {
                            Id = 8,
                            Category = "Protein",
                            Description = "Value whey.",
                            ImageUrl = "/products/warrior-whey.jpg",
                            Name = "Warrior Whey Protein",
                            Price = 42m,
                            SubCategory = "Whey",
                            Weight = "2.2 lbs"
                        },
                        new
                        {
                            Id = 9,
                            Category = "Protein",
                            Description = "Pure isolate.",
                            ImageUrl = "/products/iso-hearn.jpg",
                            Name = "ISO Hearn Protein",
                            Price = 68m,
                            SubCategory = "Isolate",
                            Weight = "4.9 lbs"
                        },
                        new
                        {
                            Id = 10,
                            Category = "Protein",
                            Description = "Zero sugar.",
                            ImageUrl = "/products/challenger-whey-isolate.jpg",
                            Name = "Challenger Whey Isolate",
                            Price = 63m,
                            SubCategory = "Isolate",
                            Weight = "4.4 lbs"
                        },
                        new
                        {
                            Id = 11,
                            Category = "Protein",
                            Description = "Chocolate brownie bar.",
                            ImageUrl = "/products/quest-brownie.jpg",
                            Name = "Quest Brownie Bar",
                            Price = 4m,
                            SubCategory = "Bar",
                            Weight = "60g"
                        },
                        new
                        {
                            Id = 12,
                            Category = "Protein",
                            Description = "Cookie dough bar.",
                            ImageUrl = "/products/quest-cookie-dough.jpg",
                            Name = "Quest Cookie Dough Bar",
                            Price = 4m,
                            SubCategory = "Bar",
                            Weight = "60g"
                        },
                        new
                        {
                            Id = 13,
                            Category = "Protein",
                            Description = "Cookies & cream.",
                            ImageUrl = "/products/quest-cookies-cream.jpg",
                            Name = "Quest Cookies & Cream Bar",
                            Price = 4m,
                            SubCategory = "Bar",
                            Weight = "60g"
                        },
                        new
                        {
                            Id = 14,
                            Category = "Protein",
                            Description = "Soft cookie.",
                            ImageUrl = "/products/quest-double-chocolate-cookie.jpg",
                            Name = "Quest Double Chocolate Cookie",
                            Price = 4m,
                            SubCategory = "Bar",
                            Weight = "59g"
                        },
                        new
                        {
                            Id = 15,
                            Category = "Protein",
                            Description = "Peanut butter.",
                            ImageUrl = "/products/quest-protein-bar-chocolate-peanut.jpg",
                            Name = "Quest Peanut Butter Bar",
                            Price = 4m,
                            SubCategory = "Bar",
                            Weight = "60g"
                        },
                        new
                        {
                            Id = 33,
                            Category = "Protein",
                            Description = "Mint chocolate protein bar.",
                            ImageUrl = "/products/fitcrunch-mint.jpg",
                            Name = "FitCrunch Mint Chocolate",
                            Price = 3m,
                            SubCategory = "Bar",
                            Weight = "46g"
                        },
                        new
                        {
                            Id = 34,
                            Category = "Protein",
                            Description = "White chocolate raspberry bar.",
                            ImageUrl = "/products/quest-white-raspberry.jpg",
                            Name = "Quest White Raspberry",
                            Price = 4m,
                            SubCategory = "Bar",
                            Weight = "60g"
                        },
                        new
                        {
                            Id = 35,
                            Category = "Protein",
                            Description = "Crunchy protein bar.",
                            ImageUrl = "/products/crunch-bar.jpg",
                            Name = "Crunch Protein Bar",
                            Price = 3m,
                            SubCategory = "Bar",
                            Weight = "60g"
                        },
                        new
                        {
                            Id = 36,
                            Category = "Protein",
                            Description = "Chocolate brownie protein bar.",
                            ImageUrl = "/products/fitcrunch-brownie.jpg",
                            Name = "FitCrunch Chocolate Brownie",
                            Price = 3m,
                            SubCategory = "Bar",
                            Weight = "46g"
                        },
                        new
                        {
                            Id = 16,
                            Category = "Gainer",
                            Description = "High calorie.",
                            ImageUrl = "/products/critical-mass.jpg",
                            Name = "Critical Mass Gainer",
                            Price = 75m,
                            SubCategory = "Mass",
                            Weight = "6 kg"
                        },
                        new
                        {
                            Id = 17,
                            Category = "Gainer",
                            Description = "All in one.",
                            ImageUrl = "/products/hard-mass-gainer.jpg",
                            Name = "Hard Mass Gainer",
                            Price = 80m,
                            SubCategory = "Mass",
                            Weight = "12 lbs"
                        },
                        new
                        {
                            Id = 18,
                            Category = "Carbs",
                            Description = "Fast carbs.",
                            ImageUrl = "/products/carbox.jpg",
                            Name = "Carbox Carb Powder",
                            Price = 30m,
                            SubCategory = "Carb",
                            Weight = "1 kg"
                        },
                        new
                        {
                            Id = 19,
                            Category = "Creatine",
                            Description = "Micronized.",
                            ImageUrl = "/products/nutrex-creatine.jpg",
                            Name = "Nutrex Creatine",
                            Price = 25m,
                            SubCategory = "Monohydrate",
                            Weight = "300g"
                        },
                        new
                        {
                            Id = 20,
                            Category = "Creatine",
                            Description = "Pure creatine.",
                            ImageUrl = "/products/scitec-creatine.jpg",
                            Name = "Scitec Creatine",
                            Price = 27m,
                            SubCategory = "Monohydrate",
                            Weight = "300g"
                        },
                        new
                        {
                            Id = 21,
                            Category = "Creatine",
                            Description = "Beauty blend.",
                            ImageUrl = "/products/nutrex-creatine-women.jpg",
                            Name = "Creatine for Women",
                            Price = 29m,
                            SubCategory = "Blend",
                            Weight = "330g"
                        },
                        new
                        {
                            Id = 22,
                            Category = "Creatine",
                            Description = "Strength.",
                            ImageUrl = "/products/challenger-creatine.jpg",
                            Name = "Challenger Creatine",
                            Price = 24m,
                            SubCategory = "Monohydrate",
                            Weight = "300g"
                        },
                        new
                        {
                            Id = 23,
                            Category = "Amino",
                            Description = "Hydration.",
                            ImageUrl = "/products/nutrex-eaa-hydration.jpg",
                            Name = "Nutrex EAA Hydration",
                            Price = 35m,
                            SubCategory = "EAA",
                            Weight = "390g"
                        },
                        new
                        {
                            Id = 24,
                            Category = "Amino",
                            Description = "Recovery.",
                            ImageUrl = "/products/nutritech-amino-boost.jpg",
                            Name = "Nutritech Amino Boost",
                            Price = 32m,
                            SubCategory = "Amino",
                            Weight = "400g"
                        },
                        new
                        {
                            Id = 41,
                            Category = "Amino",
                            Description = "BCAA recovery support.",
                            ImageUrl = "/products/bcaa-rule1.jpg",
                            Name = "Rule One BCAA",
                            Price = 32m,
                            SubCategory = "BCAA",
                            Weight = "30 Servings"
                        },
                        new
                        {
                            Id = 47,
                            Category = "Amino",
                            Description = "Pump support.",
                            ImageUrl = "/products/1-arginine.jpg",
                            Name = "Nutrex L-Arginine",
                            Price = 27m,
                            SubCategory = "Nitric Oxide",
                            Weight = "120 Capsules"
                        },
                        new
                        {
                            Id = 25,
                            Category = "Vitamins",
                            Description = "ZMA.",
                            ImageUrl = "/products/quamtrax-zma.jpg",
                            Name = "Quamtrax ZMA",
                            Price = 20m,
                            SubCategory = "ZMA",
                            Weight = "90 Capsules"
                        },
                        new
                        {
                            Id = 26,
                            Category = "Vitamins",
                            Description = "Omega 3.",
                            ImageUrl = "/products/ruleone-fish-oil.jpg",
                            Name = "Rule One Fish Oil",
                            Price = 18m,
                            SubCategory = "Fish Oil",
                            Weight = "100 Softgels"
                        },
                        new
                        {
                            Id = 27,
                            Category = "Vitamins",
                            Description = "Daily vitamins.",
                            ImageUrl = "/products/muscletech-platinum-multivitamin.jpg",
                            Name = "MuscleTech Multivitamin",
                            Price = 22m,
                            SubCategory = "Multivitamin",
                            Weight = "90 Tablets"
                        },
                        new
                        {
                            Id = 28,
                            Category = "Vitamins",
                            Description = "Men health.",
                            ImageUrl = "/products/mens-multi.jpg",
                            Name = "Men's Multivitamin",
                            Price = 24m,
                            SubCategory = "Multivitamin",
                            Weight = "90 Tablets"
                        },
                        new
                        {
                            Id = 29,
                            Category = "Vitamins",
                            Description = "Women health.",
                            ImageUrl = "/products/womens-multi.jpg",
                            Name = "Women's Multivitamin",
                            Price = 24m,
                            SubCategory = "Multivitamin",
                            Weight = "60 Tablets"
                        },
                        new
                        {
                            Id = 30,
                            Category = "Health",
                            Description = "Organic moringa.",
                            ImageUrl = "/products/organic-moringa.jpg",
                            Name = "Organic Moringa Powder",
                            Price = 19m,
                            SubCategory = "Superfood",
                            Weight = "200g"
                        },
                        new
                        {
                            Id = 31,
                            Category = "Health",
                            Description = "Testosterone.",
                            ImageUrl = "/products/tongkat-ali.jpg",
                            Name = "Tongkat Ali",
                            Price = 28m,
                            SubCategory = "Herbal",
                            Weight = "120 Capsules"
                        },
                        new
                        {
                            Id = 32,
                            Category = "Health",
                            Description = "Stress.",
                            ImageUrl = "/products/ashwagandha.jpg",
                            Name = "Ashwagandha",
                            Price = 26m,
                            SubCategory = "Herbal",
                            Weight = "60 Capsules"
                        },
                        new
                        {
                            Id = 37,
                            Category = "Health",
                            Description = "CLA fat support.",
                            ImageUrl = "/products/cla.jpg",
                            Name = "Allmax CLA",
                            Price = 28m,
                            SubCategory = "Fat Support",
                            Weight = "150 Softgels"
                        },
                        new
                        {
                            Id = 38,
                            Category = "Health",
                            Description = "Recovery support.",
                            ImageUrl = "/products/glutamine.jpg",
                            Name = "Glutamine",
                            Price = 28m,
                            SubCategory = "Recovery Support",
                            Weight = "390g"
                        },
                        new
                        {
                            Id = 39,
                            Category = "Health",
                            Description = "Muscle supplement.",
                            ImageUrl = "/products/biotech-hmb.jpg",
                            Name = "HMB",
                            Price = 28m,
                            SubCategory = "Muscle Support",
                            Weight = "30 Servings"
                        },
                        new
                        {
                            Id = 42,
                            Category = "Health",
                            Description = "Metabolic support.",
                            ImageUrl = "/products/berberine.jpg",
                            Name = "Berberine",
                            Price = 25m,
                            SubCategory = "Metabolism",
                            Weight = "60 Capsules"
                        },
                        new
                        {
                            Id = 51,
                            Category = "Health",
                            Description = "Collagen support.",
                            ImageUrl = "/products/ultra-collagen.jpg",
                            Name = "Ultra Collagen Grass Fed Peptides",
                            Price = 34m,
                            SubCategory = "Collagen",
                            Weight = "198 g"
                        },
                        new
                        {
                            Id = 40,
                            Category = "Hydration",
                            Description = "Electrolyte hydration.",
                            ImageUrl = "/products/1lytes.jpg",
                            Name = "Rule One 1LYTES",
                            Price = 28m,
                            SubCategory = "Electrolytes",
                            Weight = "40 Servings"
                        },
                        new
                        {
                            Id = 43,
                            Category = "Fat Burner",
                            Description = "Thermogenic fat burner.",
                            ImageUrl = "/products/lipo6-black.jpg",
                            Name = "Nutrex Lipo-6 Black",
                            Price = 38m,
                            SubCategory = "Thermogenic",
                            Weight = "60 Capsules"
                        },
                        new
                        {
                            Id = 48,
                            Category = "Fat Burner",
                            Description = "Body composition.",
                            ImageUrl = "/products/bpi-cla.jpg",
                            Name = "BPI Sports CLA",
                            Price = 28m,
                            SubCategory = "CLA",
                            Weight = "150 Softgels"
                        },
                        new
                        {
                            Id = 44,
                            Category = "Pre-Workout",
                            Description = "High energy.",
                            ImageUrl = "/products/total-war.jpg",
                            Name = "Redcon1 Total War",
                            Price = 45m,
                            SubCategory = "High Stim",
                            Weight = "30 Servings"
                        },
                        new
                        {
                            Id = 45,
                            Category = "Pre-Workout",
                            Description = "Alternate flavor.",
                            ImageUrl = "/products/total-wr.jpg",
                            Name = "Redcon1 Total War (Alt)",
                            Price = 45m,
                            SubCategory = "High Stim",
                            Weight = "30 Servings"
                        },
                        new
                        {
                            Id = 49,
                            Category = "Pre-Workout",
                            Description = "Stim-free pump.",
                            ImageUrl = "/products/moons-truck-zero.jpg",
                            Name = "Moons Truck Zero",
                            Price = 42m,
                            SubCategory = "Stim Free",
                            Weight = "30 Servings"
                        },
                        new
                        {
                            Id = 50,
                            Category = "Pre-Workout",
                            Description = "Energy & focus.",
                            ImageUrl = "/products/C4.jpg",
                            Name = "C4 Original Pre-Workout",
                            Price = 45m,
                            SubCategory = "Energy & Focus",
                            Weight = "50 Servings"
                        });
                });

            modelBuilder.Entity("ProteinStore.API.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("ProteinStore.API.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("OrderId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("ProteinStore.API.Models.OrderItem", b =>
                {
                    b.HasOne("ProteinStore.API.Models.Order", null)
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId");

                    b.HasOne("Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ProteinStore.API.Models.Order", b =>
                {
                    b.Navigation("OrderItems");
                });
#pragma warning restore 612, 618
        }
    }
}
